Feat/group names
GeorgeKontsevik/sloyka pull request #34
Opened 2024-05-16 10:00 UTC by Voronapxl

1. Added area_matcher method, that compares municipal names with group names from incoming dataframe from parser 
2. Added test for area matcher

2024-05-16 20:03 UTC, GeorgeKontsevik commented
А можешь плес отдельным коммитом все тесты пока убрать которые есть? Всм или закоммитить или просто в воркфлоу закоммитить чтобы он их е прогонял? Кстати почему-то не увидел твоего теста при прогоне тестов

2024-05-16 20:05 UTC, GeorgeKontsevik commented
E   ModuleNotFoundError: No module named 'osmapi'

кажется что-то в зависимости не добавили (можно просто через поетри адд) но странно зачем конкретно этот модуль нужен? оверпай и осмнх тут не подойдут?

2024-05-16 20:08 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +class AreaMatcher:
нужно добавить докстринги. Можно проверить базаров качество кода через команду в Лэйк файле которая вызовет пайлинт и Блэк кажется

2024-05-16 20:09 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +            date = "2024-04-22T00:00:00Z"
не знаю что это за теги и дата но имхо такое лучше не хардкодить + назвать понятнеее

2024-05-16 20:10 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +    def get_df_areas(self, osm_id):
эту и другие функции нужно разбить на функции поменьше чтобы условно каждая делала одно что-то

2024-05-16 20:10 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        return self.area_cache[osm_id]
а зачем возвращать если оно в селф и так хранится? мб лучше тогда не хранить в селф?

2024-05-16 20:11 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        words_to_remove = ["сельское поселение", "городское поселение", "район", "округ", "город"]
в константы

2024-05-16 20:11 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        group_name = re.sub(r'[\"!?\u2665\u2022()|,.-:]', '', group_name)
и мб это тоже хз тут год захардкодили

2024-05-16 20:11 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        words_to_remove_f_groups = [
тоже

2024-05-16 20:26 UTC, GeorgeKontsevik requested changes

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +
функция ту мач большая в какой-то момент потерял нить что происходит

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +    def _get_place_from_id(self, osm_id, osm_type):
имхо так может так и оставить зачем отдельно выносить? но тут хз мб так лучше

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            except Exception as e:
нужно указать конкретную ошибку

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +    def get_features_from_id(
а зачем селфи тут везде? можно попробовать через имя класса обращаться тк у класса самого ниче глобально вроде не хранится

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            ox.settings.overpass_endpoint = "https://overpass-api.de/api"
сеттинги надо подумать где-то глобально определять а то внутри функции ну такое имхо

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        MyApi = OsmApi()
кажется экземпляр класс осмапи уже где-то создавался?

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        gdf.geometry.dropna(inplace=True)
а тут могут быть нан геометрии?

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        tmpgdf["centroid"] = tmpgdf["geometry"].centroid
не понял зачем тут тмпгдф

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        tmpgdf = None
еще можно писать del tmpgdf

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            return None
что произойдет дальше если будет нан? имхо стоит сделать класс с кастовыми ошибками и их рейзить

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        'v': '5.131'
хардкод

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        response = requests.get('https://api.vk.com/method/groups.getById', params=params)
хардкод

2024-05-16 20:26 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        "v": VKParser.API_VERISON,
а поч тут версия капи через константу а выше захардкожена?))

2024-05-16 20:26 UTC, GeorgeKontsevik commented on tests/test_area_matcher.py
> +    access_token = '...'
я хз как такое тестить ес чес без токена
мб скипнуть все где требуются токены?

2024-05-16 20:26 UTC, GeorgeKontsevik commented on tests/test_area_matcher.py
> +    osm_id = 337422
можно выбрать мб самую самую маленькую зону типа Тары например условно

2024-05-16 20:26 UTC, GeorgeKontsevik commented on tests/test_area_matcher.py
> +    assert any(test_df_groups['territory'].apply(lambda x: bool(re.search(r'Колпин', x))))
имхо если что вернуло то уже хорошо

2024-05-16 20:26 UTC, GeorgeKontsevik commented on tests/test_semantic_graph.py
> +#import pandas as pd
просто скажи что Леня в курсе))

2024-05-16 20:50 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +            date = "2024-04-22T00:00:00Z"
Про дату согласен. Про теги ен знаю как лучше, это теги административных уровней, чтобы выгрузить названия районов, округов, поселений и т.д.

2024-05-16 20:52 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +
Я возможно уберу " if has_digits" потому что оно криво рабоает, всё равно названия типа "МО №15" не разбирает

2024-05-16 20:58 UTC, Voronapxl commented on tests/test_semantic_graph.py
> +#import pandas as pd
Лёня в курсе, пока будет закомменчен. Лёня позже перепишет

2024-05-16 20:59 UTC, Voronapxl commented on tests/test_area_matcher.py
> +    assert any(test_df_groups['territory'].apply(lambda x: bool(re.search(r'Колпин', x))))
Оно возвращает, просто хотелось узнать что то что жду

2024-05-16 21:00 UTC, Voronapxl commented on tests/test_area_matcher.py
> +    access_token = '...'
Просто нужен датафрейм, где будет столбец group_name с названиями групп. В принципе прям парсер использовать не принципиально

2024-05-16 21:01 UTC, Voronapxl commented on sloyka/src/data_getter.py
> +        "v": VKParser.API_VERISON,
Мой косяк, поправлю

2024-05-16 21:07 UTC, Voronapxl commented on sloyka/src/data_getter.py
> +        tmpgdf["centroid"] = tmpgdf["geometry"].centroid
Это из одной системы проекции в другую перегоняет. Поэтому там в центроидах координаты другие по сравнению с точками. Возможно, вообще стоит убрать. Я помню мы в декабре это обсуждали но не решили что с этим делать

2024-05-16 21:10 UTC, Voronapxl commented on sloyka/src/data_getter.py
> +        MyApi = OsmApi()
Не совсем понял о чём ты. Я вижу только один во всём коде

2024-05-17 09:28 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +            date = "2024-04-22T00:00:00Z"
они там раз на раз не приходятся к сожалению

2024-05-17 15:31 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +            date = "2024-04-22T00:00:00Z"
Я сделал, что теги и дата подаётся на вход

2024-05-17 15:31 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +    def get_df_areas(self, osm_id):
Разбил на функции поменьше

2024-05-17 15:32 UTC, Voronapxl commented on sloyka/src/data_getter.py
> +        "v": VKParser.API_VERISON,
Поправил, вроде везде через константу прописал

2024-05-17 15:33 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +
Убрал gas_digits

2024-05-30 13:19 UTC, Voronapxl commented
> E ModuleNotFoundError: No module named 'osmapi'
> 
> кажется что-то в зависимости не добавили (можно просто через поетри адд) но странно зачем конкретно этот модуль нужен? оверпай и осмнх тут не подойдут?

Вспомнил, в чём проблема. У этих модулей не нашёл свтроенного функционала для получения доступа к истории объектов. А у osmapi он есть, поэтому тогдарешил использовать его

2024-05-31 08:54 UTC, LeonDeTur commented on sloyka/src/geocoder.py
> +        for i, group_name in enumerate(df['group_name']):
Простите, что влезаю, но вот это формально хардкод.

2024-05-31 08:55 UTC, LeonDeTur commented on sloyka/src/geocoder.py
> +    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "Текст комментария"):
```suggestion
    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "text"):
```

2024-05-31 08:55 UTC, LeonDeTur commented on sloyka/src/geocoder.py
> +        for i, group_name in enumerate(df['group_name']):
```suggestion
        for i, group_name in enumerate(df[group_name]):
```

2024-05-31 08:56 UTC, LeonDeTur commented on sloyka/src/geocoder.py
> +    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "Текст комментария"):
```suggestion
    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "text", froup_column: str = "group_name"):
```

2024-05-31 08:59 UTC, LeonDeTur commented on sloyka/src/geocoder.py
> +    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "text", froup_column: str = "group_name"):
```suggestion
    def run(self, osm_id, tags, date, df: pd.DataFrame, text_column: str = "text", group_column: str = "group_name"):
```

2024-06-03 09:03 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +    def _get_place_from_id(self, osm_id, osm_type):
думал что можно просто без отдельной функции это делать

2024-06-05 10:16 UTC, GeorgeKontsevik requested changes

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +    def get_features_from_id(
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        group_name = re.sub(r'[\"!?\u2665\u2022()|,.-:]', '', group_name)
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +        return self.area_cache[osm_id]
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/area_matcher.py
> +class AreaMatcher:
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            except Exception as e:
кажется нужно еще раз тут проверить что это решено

всм там не е а IndexError  условно всм что ты ожидаешь что-то конкретное и тогда ок что оно тут вылетело и идешь дальше а если чот другое ну тогда беда беда

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        gdf.geometry.dropna(inplace=True)
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        gdf.geometry.dropna(inplace=True)
всм если нан то что? кажется дальше сломается не?

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        tmpgdf["centroid"] = tmpgdf["geometry"].centroid
короче это странно выглядит как думаешь сможем же без этого обойтись?

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +        tmpgdf = None
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            return None
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            return None
костомными*

2024-06-05 10:16 UTC, GeorgeKontsevik commented on sloyka/src/data_getter.py
> +            return None
+ использовать логуру а не принты

2024-06-05 10:16 UTC, GeorgeKontsevik commented on tests/test_area_matcher.py
> +    osm_id = 337422
кажется нужно еще раз тут проверить что это решено

2024-06-05 10:16 UTC, GeorgeKontsevik commented on tests/test_area_matcher.py
> +    osm_id = 337422
давай все же айдишник не хардкодить и это все еще питер не?

2024-06-05 10:16 UTC, GeorgeKontsevik commented on tests/test_geocoder.py
> +from sloyka.src.geocoder import Geocoder
а как раньше не работало хмм

2024-06-05 10:17 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +class AreaMatcher:
Его больше не существует, я просто перенёс функционал в геокодер

2024-06-05 10:18 UTC, Voronapxl commented on sloyka/src/area_matcher.py
> +        group_name = re.sub(r'[\"!?\u2665\u2022()|,.-:]', '', group_name)
Я перенёс в константы
![image](https://github.com/GeorgeKontsevik/sloyka/assets/142047864/62d0beeb-d68c-4ca3-a36d-e43c7bdcfa12)

2024-06-05 10:19 UTC, Voronapxl commented on tests/test_area_matcher.py
> +    osm_id = 337422
Area_matcher больше не существует, он интегрирован в геокодер, там это решил

2024-06-05 10:21 UTC, Voronapxl commented on tests/test_geocoder.py
> +from sloyka.src.geocoder import Geocoder
Возможно, что через установленную в пип либу. У меня выдавало ошибку импорта, поэтому так

2024-06-05 10:23 UTC, Voronapxl commented on tests/test_area_matcher.py
> +    osm_id = 337422
Точнее он существует, но не будет использоваться, пардон. В будущем я удалю этот файл

2024-06-07 12:45 UTC, Voronapxl commented on sloyka/src/data_getter.py
> +    def get_features_from_id(
![image](https://github.com/GeorgeKontsevik/sloyka/assets/142047864/8658ea62-d300-4ceb-9106-7b0b1dfa623d)
Где надо поменял это

2024-06-08 13:40 UTC, GeorgeKontsevik approved these changes
LGTM!

2024-06-08 13:40 UTC, merged